"""Generates the Tylenol bottle cosmetic's label texture.

Draws the wrap-around label (an original recreation, not the retail artwork)
at 2x and downsamples to 4096x1440 for crisp anti-aliased text, then writes
tylenol_label.png plus tylenol_label_png.h (the PNG bytes as a C array, decoded
at run time). Uses fonts that ship with Windows. Re-run after editing:
    python src/native/cosmetics/gen_tylenol_label.py
"""
import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts")
S = 2                      # supersample factor
W, H = 4096 * S, 1440 * S  # final 4096x1440 wraps the full bottle body
U = W / 2048.0             # layout units from the 2048x720 web demo

RED = (215, 25, 32)
GOLD = (242, 183, 5)
NAVY = (18, 58, 115)
INK = (27, 27, 27)
PAPER = (251, 251, 248)


def font(name, px, variation=None):
    f = ImageFont.truetype(os.path.join(FONTS, name), int(px * U))
    if variation:
        f.set_variation_by_name(variation)
    return f


def text_center(d, xy, s, f, fill):
    d.text((xy[0] * U, xy[1] * U), s, font=f, fill=fill, anchor="mm")


def text_left(d, xy, s, f, fill):
    d.text((xy[0] * U, xy[1] * U), s, font=f, fill=fill, anchor="ls")


def rrect(d, x, y, w, h, r, **kw):
    d.rounded_rectangle([x * U, y * U, (x + w) * U, (y + h) * U], radius=r * U, **kw)


def fit_font(d, s, name, px, max_w, variation=None):
    f = font(name, px, variation)
    w = d.textlength(s, font=f) / U
    if w > max_w:
        f = font(name, px * max_w / w, variation)
    return f


def drug_facts(d, x, y, w):
    text_left(d, (x, y), "Drug Facts", font("bahnschrift.ttf", 46, "Bold Condensed"), INK)
    d.rectangle([x * U, (y + 14) * U, (x + w) * U, (y + 20) * U], fill=INK)
    for i, f in enumerate([0.92, 0.78, 0.86, 0.6, 0.9, 0.7]):
        c = (85, 85, 85) if i % 3 == 0 else (140, 140, 140)
        yy = y + 52 + i * 30
        d.rectangle([x * U, yy * U, (x + w * f) * U, (yy + 12) * U], fill=c)


def barcode(d, x, y, w, h):
    d.rectangle([(x - 16) * U, (y - 12) * U, (x + w + 16) * U, (y + h + 28) * U], fill=(255, 255, 255))
    cx, seed = x, 7
    while cx < x + w:
        seed = (seed * 16807) % 2147483647
        bw = 2 + seed % 5
        if seed % 3:
            d.rectangle([cx * U, y * U, (cx + bw) * U, (y + h) * U], fill=(17, 17, 17))
        cx += bw + 2


img = Image.new("RGB", (W, H), PAPER)
d = ImageDraw.Draw(img)
fx, fw = 512, 1024  # front panel = middle half of the wrap (layout units)

# Red header band + gold keyline across the whole wrap.
d.rectangle([0, 0, W, 250 * U], fill=RED)
d.rectangle([0, 250 * U, W, 260 * U], fill=GOLD)

# TYLENOL plaque.
px, py, pw, ph = fx + 70, 34, fw - 140, 182
rrect(d, px, py, pw, ph, 26, fill=(255, 255, 255))
rrect(d, px + 10, py + 10, pw - 20, ph - 20, 18, outline=GOLD, width=int(8 * U))
text_center(d, (fx + fw / 2, py + ph / 2 + 6), "TYLENOL", fit_font(d, "TYLENOL", "ariblk.ttf", 140, pw - 90), RED)

# 8 HOUR badge.
bx, by = fx + 170, 430
d.ellipse([(bx - 118) * U, (by - 118) * U, (bx + 118) * U, (by + 118) * U], fill=NAVY)
d.ellipse([(bx - 104) * U, (by - 104) * U, (bx + 104) * U, (by + 104) * U], outline=GOLD, width=int(10 * U))
text_center(d, (bx, by - 22), "8", font("ariblk.ttf", 118), (255, 255, 255))
text_center(d, (bx, by + 62), "HOUR", font("bahnschrift.ttf", 50, "Bold Condensed"), (255, 255, 255))

# Product name + copy.
text_left(d, (fx + 320, 378), "ARTHRITIS PAIN", fit_font(d, "ARTHRITIS PAIN", "bahnschrift.ttf", 118, fw - 360, "Bold Condensed"), NAVY)
text_left(d, (fx + 324, 440), "Acetaminophen Extended-Release", font("segoeui.ttf", 40), INK)
text_left(d, (fx + 324, 488), "Tablets, 650 mg", font("segoeui.ttf", 40), INK)
text_left(d, (fx + 324, 545), "PAIN RELIEVER / FEVER REDUCER", font("bahnschrift.ttf", 40, "SemiBold Condensed"), RED)

# 100 CAPLETS pill + claim.
rrect(d, fx + fw - 420, 590, 360, 96, 48, fill=RED)
text_center(d, (fx + fw - 240, 638), "100 CAPLETS", font("bahnschrift.ttf", 64, "Bold Condensed"), (255, 255, 255))
text_left(d, (fx + 72, 652), "LASTS UP TO 8 HOURS", font("bahnschrift.ttf", 38, "SemiBold Condensed"), NAVY)

# Back panel: drug facts on both sides of the seam + barcode.
drug_facts(d, 60, 300, 2048 * 0.25 - 110)
drug_facts(d, 2048 * 0.75 + 50, 300, 2048 * 0.25 - 110)
barcode(d, 2048 * 0.75 + 80, 580, 300, 100)

img = img.resize((W // S, H // S), Image.LANCZOS)
png_path = os.path.join(HERE, "tylenol_label.png")
img.save(png_path, optimize=True)
data = open(png_path, "rb").read()

hdr_path = os.path.join(HERE, "tylenol_label_png.h")
with open(hdr_path, "w", newline="\n") as f:
    f.write("// Generated by gen_tylenol_label.py -- do not edit.\n")
    f.write("// Tylenol bottle cosmetic label, 4096x1440 PNG (original recreation).\n")
    f.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
    f.write("namespace skate3::cosmetics {\n\n")
    f.write("inline constexpr uint8_t kTylenolLabelPng[] = {\n")
    for i in range(0, len(data), 24):
        f.write("  " + ",".join("0x%02X" % b for b in data[i:i + 24]) + ",\n")
    f.write("};\ninline constexpr size_t kTylenolLabelPngSize = sizeof(kTylenolLabelPng);\n\n")
    f.write("}  // namespace skate3::cosmetics\n")
print("wrote", png_path, len(data), "bytes and", hdr_path)
